Module2 task2
htmlacademy-yii/794021-task-force-1 pull request #5
Opened 2021-07-31 16:00 UTC by rrramble

2021-08-02 05:47 UTC, olegmifle requested changes

2021-08-02 05:47 UTC, olegmifle commented on sql/schema.sql
>    DEFAULT COLLATE utf8_general_ci
Для каждой таблицы указывать явно нет смысла, если там нет ничего особенного. Обычно это указывается на уровне БД и всё.

2021-08-02 05:47 UTC, olegmifle commented on src/actions/AbstractAction.php
> +namespace R794021\Actions;
Что такое `R794021`?

2021-08-02 05:47 UTC, olegmifle commented on src/actions/AbstractAction.php
> +    static protected $internalCodename;
Почему статичные?

2021-08-02 05:47 UTC, olegmifle commented on src/actions/Apply.php
> +class Apply extends AbstractAction
Думаю ApplyAction было бы лучше.

2021-08-02 05:47 UTC, olegmifle commented on src/actions/Apply.php
> +    public function isValid(Users\User $user, Tasks\Task $task): bool
Лучше не писать такие составные неймспейсы в тайпхинтах. Лучше экспортируй в `use` и оставь тут уже конечный тип.

2021-08-02 05:47 UTC, olegmifle commented on src/actions/Apply.php
> +    }
Можно ещё вот так
```suggestion
        return $task->getStatus() === Task::STATUS_NEW ? $user->isContractor() : false;
    }
```

2021-08-02 05:47 UTC, olegmifle commented on src/tasks/Task.php
> +            throw new \Error('Unknown status.');
Исключения нужно называть с постфиксом `Exception`. Но и ErrorException будет так себе название. Можно попробовать такую логику: если проблемы с параметрами (в роутах или где-то ещё на верхних слоях приложения), то можно отдать InvalidArgumentException, если проблемы типа неизвестный статус и в таком роде, то DomainException

2021-08-02 05:47 UTC, olegmifle commented on src/tasks/Task.php
> +    public const ACTION_REJECT = 'reject';
Ты ж это всё унёс в классы-статусы? Это уже дублирование получается.

2021-08-02 05:47 UTC, olegmifle commented on src/tests/actions/Apply.test.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
Вообще `$_SERVER['DOCUMENT_ROOT']` не всегда удобен. Например при запуске скрипта по крону DOCUMENT_ROOT не определён. Можно использовать` __DIR__` и от этого строить путь. Или можно явно определить DOCUMENT_ROOT где-то во входном скрипте. Тут, наверное, можно и не менять. Это скорее для общего развития)

2021-08-02 05:47 UTC, olegmifle commented on src/tests/actions/Apply.test.php
> +$customer2 = new Users\Customer(['id' => 13]);
Что такое 12, 24, 13? Магические числа?)

2021-08-02 05:47 UTC, olegmifle commented on src/tests/actions/Apply.test.php
> +<?php
А почему через точку названы скрипты?

2021-08-02 05:47 UTC, olegmifle commented on src/users/AbstractUser.php
> +    abstract static function isCustomer(): bool;
Кроме юзера и заказчика предполагаются ещё другие пользователи с такими ролями?

2021-08-02 05:47 UTC, olegmifle commented on src/users/AbstractUser.php
> +    abstract static function isCustomer(): bool;
Вообще я бы сделал метод getRole() которая б отдавал роль, ну отдельно класс с константами ролей

2021-08-02 06:10 UTC, rrramble commented on src/actions/AbstractAction.php
> +namespace R794021\Actions;
Уникальный номер id студента в HtmlAcademy

2021-08-02 06:15 UTC, rrramble commented on src/actions/AbstractAction.php
> +    static protected $internalCodename;
Каждый экземпляр класс действия должен иметь едины и неизменный эти два поля. То есть: $apply1 и $apply2 (класса 'Apply') должны иметь единое имя 'Откликнуться' и единый внутренний код 'apply'.

2021-08-02 06:30 UTC, rrramble commented on src/actions/Apply.php
> +    }
Высокая когнитивная нагрузка.

Если на то пошло, то лучше даже так:
return
	$task->getStatus() === Tasks\Task::STATUS_NEW
	&& $user->isContractor();

Был бы JS, согласен, из-за отсутствия символов легче понять:
return
	task.status === Task.STATUS_NEW
	&& user.isContractor;

2021-08-02 06:34 UTC, rrramble commented on src/tests/actions/Apply.test.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
При тестировании это учтено, см. /src/tests/run_all.php

2021-08-02 06:38 UTC, rrramble commented on src/tests/actions/Apply.test.php
> +<?php
Облегчить восприятие. Или есть стандарт?

2021-08-02 06:53 UTC, rrramble commented on src/tasks/Task.php
> +            throw new \Error('Unknown status.');
Ну да, это не ошибка языка (Error), а ошибка логики (Exception). Но когда сделал стандартый \Exception линтер потребовал сделать свои классы исключений. Решил перехетрить линтер через Error.

2021-08-03 17:32 UTC, rrramble commented on src/tasks/Task.php
> +            throw new \Error('Unknown status.');
\ValueError? По смыслу подходит: тип правильный, но значение неверное.

2021-08-03 19:35 UTC, rrramble commented on src/users/AbstractUser.php
> +    abstract static function isCustomer(): bool;
Пока в заданиях не было про расширение типа классов кроме действий (Actions).

2021-08-04 05:24 UTC, olegmifle commented on src/actions/AbstractAction.php
> +namespace R794021\Actions;
Это не нужно, такое только путает.

2021-08-04 05:24 UTC, olegmifle commented on src/actions/AbstractAction.php
> +    static protected $internalCodename;
Это не отвечает на вопрос о статичности. Если ты уберёшь ключевое слово, то ничего не изменится.

2021-08-04 05:24 UTC, olegmifle commented on src/tasks/Task.php
> + */
Это не нужно

2021-08-04 05:24 UTC, olegmifle commented on src/users/AbstractUser.php
> +    abstract static function isCustomer(): bool;
Тогда предлагаю вообще удалить. Есть такой принцип - [YAGNI](https://ru.wikipedia.org/wiki/YAGNI), очень важный.

2021-08-04 05:24 UTC, olegmifle commented on src/actions/Action.php
> +namespace R794021\Actions;
Кстати, директории так же называются в единственном числе.

2021-08-04 05:24 UTC, merged